learning_rate: 0.0010216943108365736
epochs: 75
batch_size: 32768
train_split: 0.8
test_split: 0.2
seed: 42
run_test: false
save_interval: 25
early_stop_patience: 10
early_stop_min_delta: 0

model: "GIN" # GAT/GATv2/GraphTransformer/SAGE/GIN
embedding_dim: 1024
hidden_dim: 512
dnabert_proj_dim: 128
heads: 2
dropout_p: 0.19911532553817834
edge_dropout_p: 0.2550676115328456
num_layers: 4

focal_loss_alpha: 0.24994183621879268
focal_loss_gamma: 2.6757684201996357
use_focal_loss: true

gpu_ids: [0,1,3]  #list of gpu ids to use, "all" to use all available gpus

checkpoint_dir: "./checkpoints"
project_name: "mus-features-subsets"

species: "mouse"  # mouse/dog/dro
k_mers: 3         # 0/3/4/5 
fam_type: "Novo"  # "Novo"/""
features_subset: "all" #none/original/structural/alg/k_mer_counts/dnabert/all
partition: "random" #random/families/two_graphs
test_species: "dog"
test_k_mers: 3
test_fam_type: "Novo"

recreate_dataset: False
use_hpo: True
experiment_mode: "features_subsets" # "basic"/"features_subsets"
n_trials: 50
